### PR TITLE
format with prettier

### PR DESCRIPTION
**Pull request by eesazahed**

### CODE REVIEW

**Comment by yusufrahmn** [comment]
Personally, I like single quotes over double quotes - @TheRedstoneRadiant what do you think?

**Comment by ghost** [comment]
Yes, the majority of our codebase is currently using single quotes.

Prettier prefers double quotes by default, but we can create a `.prettierrc` file with:
```json
{
  "singleQuote": true
}
```

May also be worth adding a `format` script and prettier as a dev dependency.

**Comment by yusufrahmn** [comment]
@eesazahed Can you please update the PR to use single quotes? Thank you.

**Comment by yusufrahmn** [comment]
Okay if I'm being completely honest, these changes seem kind of unnecessary to me - they don't really make the code look nicer...
image

**Comment by eesazahed** [comment]
It's easier to read when spread out on different lines i guess, but if you don't like it you dont have to pull it.

**Comment by ghost** [comment]
In my opinion it's good to have standards, especially with formatting. It helps to maintain readability and consistency.

**Comment by yusufrahmn** [comment]
> In my opinion it's good to have standards, especially with formatting. It helps to maintain readability and consistency.

@TheRedstoneRadiant Yeah but is it really necessary to spread the arguments for a simple function over multiple lines?

**Comment by ghost** [comment]
Yes, it's good for readability and complies with Node.js formatting standards.

**Comment by eesazahed** [comment]
@notyusufr a function may be even longer than that in some cases, so it's preferable having the parameters on seperate lines. The code should rarely go over the left half of your editor. It may take a while to get used to, though.

**Comment by yusufrahmn** [comment]
Aight then @TheRedstoneRadiant your call if you want to merge :)

**Pull request merged**
